# blocklist
branches:
  except:
  - speed

# safelist
branches:
  only:
  - master
  - fixes07

language: julia
julia:
  - 0.7

script:  
  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
  - julia -e 'Pkg.clone(pwd()); Pkg.build("Laplacians"); Pkg.test("Laplacians"; coverage=true)'
  
after_success:
  - julia -e 'cd(Pkg.dir("Laplacians")); Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'
  - julia -e 'Pkg.add("Documenter")'
  - julia -e 'cd(Pkg.dir("Laplacians")); include(joinpath("docs", "make.jl"))'
