site_name: Laplacians.jl

site_description: Graph analysis inspired by graph Laplacians and the needs of researchers at YINS

theme: mkdocs

repo_url: https://github.com/danspielman/Laplacians.jl

pages:
- Home: 'index.md'
- User Guide:
    - 'Writing your docs': 'user-guide/writing-your-docs.md'
    - 'Styling your docs': 'user-guide/styling-your-docs.md'
- About:
    - 'License': 'about/license.md'
    - 'Release Notes': 'about/release-notes.md'

pages:
- About: 'about.md'
- User Guide:
    - Using Julia: 'Julia.md'
    - Overview: 'Laplacians.md'
    - Solvers: 'solvers.md'
- API:
    - Whole API: 'wholeAPI.md'
    - graphGenerators: 'graphGeneratorsAPI.md'
    - graphOps: 'graphOpsAPI.md'
    - graphAlgs: 'graphAlgsAPI.md'
    - cutPageRank: 'cutPageRankAPI.md'

docs_dir: 'docs'

site_favicon: lambda2.ico


markdown_extensions:
  - extra
  - tables
  - fenced_code

extra_css:
  - Laplacians.css

extra_javascript:
  - https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS_HTML
  - mathjaxhelper.js


use_directory_urls: false
