site_name: Laplacians.jl

site_description: Graph analysis inspired by graph Laplacians and the needs of researchers at YINS

theme: readthedocs

repo_url: https://github.com/danspielman/Laplacians.jl

pages:
- About: 'about.md'
- User Guide:
    - Installation: 'Installation.md'
    - Using Julia: 'Julia.md'
    - Examples: 'Examples.md'
    - Sparse matrices as graphs: 'CSCgraph.md'
    - Low Stretch Spanning Trees: 'LSST.md'
    - Solvers: 'usingSolvers.md'
- Developing:
    - Devleoping Laplacians: 'Developing.md'
- API:
    - generators: 'graphGenerators.md'
    - operators: 'operators.md'
    - graphUtils: 'graphUtils.md'
    - graphAlgs : 'graphAlgs.md'
    - IO: 'IO.md'
    - pcg: 'pcg.md'
    - treeAlgs: 'treeAlgs.md'
    - akpw: 'akpw.md'
    - solvers: 'solvers.md'
    - KMP: 'kmp.md'
    - localClustering: 'localClustering.md'
    - Private Functions: 'privateFuncs.md'
    

docs_dir: 'build'

site_favicon: lambda2.ico


markdown_extensions:
  - extra
  - tables
  - fenced_code

extra_css:
  - Laplacians.css



use_directory_urls: false
